import Image from "next/image";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Syria",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <></>
  );
}
